### ISSUE TITLE
[Feature] Consider alternative framing bytes to improve UART protocol's robustness against interference

### ISSUE THREAD

**Issue by 44670** [ZhuYanzhen1/CDTP#1]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求<br> I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/ZhuYanzhen1/CDTP/blob/master/README_CN.md) 并无法自行解决问题。 I have read the [documentation](https://github.com/ZhuYanzhen1/CDTP/blob/master/README.md) and was unable to solve the issue. 

### Description

Hi there,

I've been looking into your medium capacity data transmission protocol and noticed that it uses 0xFF as both frame header and frame tail. While this is simple and straightforward, it might lead to issues in situations where the UART communication is subject to interference.

When UART communication experiences external electromagnetic interference, an unexpected low-level signal (logical 0) might appear on the line. If the receiving end misinterprets this as a start bit and continues to detect high-level signals (logical 1) in the subsequent data bits, it may erroneously interpret it as a 0xFF byte. This can result in unstable communication and reduced protocol reliability.

To enhance the UART protocol's robustness against interference, I'd recommend considering alternative byte values for the frame header and frame tail, similar to the SLIP (Serial Line IP) protocol design. Using different and less likely byte combinations due to interference will help improve data transmission reliability in noisy environments.

Thank you for your work on this project!

**Comment by ZhuYanzhen1** [comment]
Hi @44670 :
&nbsp;&nbsp;Thank you for your suggestion. The reason for choosing 0xFF as the frame header/frame tail identifier at the beginning of this protocol design is that 0xFF has a relatively low probability of appearing in the data (unless you use 0xFF to fill the null byte). I really didn't think about signal interference at the beginning. At your suggestion, I will consider using 0xA5 as the frame header/frame tail identifier and you can see this change in the next version update.
